spring.application.name=aim-tester-api
server.port=8080
server.servlet.context-path=/aim-tester-api

jwt.secret=aim-tester-secret-key-for-jwt-2026-09-25
jwt.expiration=900000

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
